spring:
  datasource:
    continue-on-error: true
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      idle-timeout: 10000
  jpa:
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: com.hazelcast.hibernate.HazelcastCacheRegionFactory
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      springframework:
        web: info
    hibernate: info
